general:
  seed: null
  # checkpoint: null # continue with weights
  checkpoint: /cluster/project/cvg/labelmaker/labelmaker-mix3d/saved/baseline_scannet200/2024-02-11_1552/4127d78f/f336f10d_3a2c/last.ckpt # 200 epoch
  freeze_backbone: false # train only last layer

  project_name: mix3d
  workspace: jiguangda
  experiment_name: baseline_scannet200

  save_dir: /cluster/project/cvg/labelmaker/labelmaker-mix3d/saved/${general.experiment_name}/${now:%Y-%m-%d_%H%M}
  # time/commit/md5(config)_uuid
  # time/experiment_id/version_uuid
  experiment_id: test_scannet200 # commit[:8], or unique from logger
  version: test_scannet200 # md5[:8] of config

  gpus: 1

defaults:
  - data: indoor
  - data/data_loaders: simple_loader
  - data/datasets: scannet200
  - data/collation_functions: voxelize_collate
  - logging: offline
  - model: baseline
  - metrics: miou
  - optimizer: adamw
  - scheduler: onecyclelr
  - trainer: trainer
  - callbacks: callbacks
  - loss: cross_entropy

hydra:
  run:
    dir: /cluster/project/cvg/labelmaker/labelmaker-mix3d/saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /cluster/project/cvg/labelmaker/labelmaker-mix3d/saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${general.save_dir}
    subdir: ${hydra.job.num}_${hydra.job.id}
